apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app: web-frontend
    demo: "k8s-healing-agent"
    scenario: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
        demo: "k8s-healing-agent"
        scenario: "1"
    spec:
      containers:
        - name: web-frontend
          image: nginx:1.99.99-nonexistent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
